---
- name: install docker in kubernetes
  hosts: node     #server details are defined in the /etc/ansible/hosts file of ansible server.
  become: true

  tasks:
      - name: create new deployment in kubernetes with Deployment.yml
        command: kubectl apply -f ./ansible/Deployment.yml
      - name: Execute the service - load Balancer
        command: kubectl apply -f ./ansible/Service.yml
        

   